import { handleErr } from "../../utils/apiError";

const addProduct = async(req,res)=>{
  try{
    
  }
  catch(err){
    return handleErr(res,err);
  }
}

export {addProduct};